# Generated by Django 6.0.2 on 2026-02-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
