# Generated by Django 6.0.2 on 2026-02-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poduto',
            new_name='Produto',
        ),
    ]
